# TODO: e2e test on GitHub Pages should run after the deployment job

name: Playwright Tests
on:
  push:
    branches: [gh-pages]
  workflow_dispatch:

jobs:
  test:
    environment: github-pages
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        env:
          SEPOLIA_RPC_URL: "${{ secrets.SEPOLIA_RPC_URL }}"
          ETHERSCAN_API_KEY: "${{ secrets.ETHERSCAN_API_KEY }}"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "latest"
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test
        env:
          CI: "true"

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: out/e2e
          retention-days: 30
