# TODO: e2e test on GitHub Pages should run after the deployment job

name: Playwright Tests
on:
  push:
    branches: [gh-pages]
  pull_request:
    branches: [gh-pages]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: "latest"

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Run Playwright tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: out/e2e
          retention-days: 30
