# 1. foundry format check
# 2. foundry tests
# 3. front format check
# 4. front unit tests
# 5. front e2e tests
name: CI

on:
  pull_request:
    branches: [gh-pages, develop]
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  foundry:
    name: Foundry Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: foundry-rs/foundry-toolchain@v1
      - run: forge fmt --check
      - run: forge build --sizes
      - run: forge test -vvv
