name: CI

on:
  pull_request:
    branches: [gh-pages, develop]
  workflow_dispatch:

env:
  NODE_ENV: production
  CI: true
  FOUNDRY_PROFILE: ci

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    environment: github-pages
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # SetUp
      - uses: foundry-rs/foundry-toolchain@v1
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ">=24"
          cache: "pnpm"

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/playwright.config.[jt]s') }}
          restore-keys: ${{ runner.os }}-playwright-

      - name: Cache Front build artifacts
        uses: actions/cache@v4
        with:
          path: front/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

      # SetUp with installation
      - run: pnpm install
      - run: pnpm --filter front exec playwright install --with-deps --only-shell

      # Tests
      - run: pnpm format:check
      - run: pnpm test
      - run: pnpm build
