name: CI

on:
  pull_request:
    branches: [gh-pages, develop]
  workflow_dispatch:

env:
  NODE_ENV: production
  CI: true
  FOUNDRY_PROFILE: ci

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    environment: github-pages
    runs-on: ubuntu-latest
    env:
      ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      SEPOLIA_RPC_URL: ${{ secrets.SEPOLIA_RPC_URL }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      # SetUp
      - uses: foundry-rs/foundry-toolchain@v1
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
      - run: pnpm install

      # Tests
      - run: pnpm format:check
      - run: pnpm build
      - run: pnpm test
